### ISSUE TITLE
Build is triggered twice when a new project is added

### ISSUE THREAD

**Issue by om26er** [canonical-websites/build.snapcraft.io#1215]
## Summary

When a new project is enabled for building using build.snapcraft.io, it triggers build on all arches *twice*. After that all subsequent builds are only triggered when a new update to a project's GitHub repo is pushed.

## Process

* On build.snapcraft.io add a new repo for auto-builds
* Once you are successfully able to do that, you will realized build is triggered twice for all architectures.

## Current and expected result

Build should be triggered once as that seems like a total waste of CPU cycles ;-)

**Comment by bartaz** [comment]
Thanks for the report.
This was already mentioned before #1205 and fixed in #1210.
But it seems that the fix didn't make into live environment yet. I'll make sure it's deployed soon.

Thanks for heads up!

**Comment by bartaz** [comment]
Should be deployed live now.

**Comment by om26er** [comment]
Ok, this isn't really fixed. I just added a new project and seems it again triggered build twice
![build-bug](https://user-images.githubusercontent.com/6350837/56169660-4f641d00-5ff8-11e9-9859-d063ae785dd7.png)

**Comment by bartaz** [comment]
@om26er Thanks for the report.

I tried to reproduce it, but for me builds where triggered only once.

Can you tell us on what repo it happens, what was the sequence of you adding it and triggering builds?
(did it have snapcraft.yaml when it was added? did registering name triggered builds or something else?).
We need some more details to see why builds are triggered twice sometimes. Thanks!
